baseURL = 'https://boxsubmus.com/'
languageCode = 'en-us'
title = 'Boxsubmus'
theme = 'boxsubmus'
canonifyURLs = true

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files, who cares?

[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
    [menus.main.params]
      icon = 'home'

[[menus.main]]
    name = 'About Us'
    pageRef = '/about'
    weight = 2
    [menus.main.params]
      icon = 'info'

[[menus.main]]
    name = 'Philosophy'
    pageRef = '/philosophy'
    weight = 3
    [menus.main.params]
      icon = 'visibility'

[[menus.main]]
    name = 'Donate'
    pageRef = '/donate'
    weight = 4
    [menus.main.params]
      icon = 'favorite'

[[menus.main]]
    name = 'Privacy Policy'
    pageRef = '/privacy'
    weight = 4
    [menus.main.params]
      icon = 'security'


# Games
[[menus.games]]
    name = 'Minesweeper+'
    pageRef = '/games/minesweeper+'
    weight = 70

# Tools